language: node_js
node_js:
  - '10.15.0'

sudo: required

services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

install:
  - docker --version
  - docker-compose --version

script:
  - npm run docker lint
  - npm run docker test

after_script:
  - npm run docker:stop
