language: node_js
node_js:
  - '10.13.0'

sudo: required

services:
  - docker

cache: npm
addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo apt-get install libsecret-1-dev

install:
  - docker --version
  - docker-compose --version
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - npm run docker lint
  - npm run docker test

after_script:
  - npm run docker:stop
