language: node_js
node_js:
  - '10.13.0'

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo apt-get install libsecret-1-dev
before_script:

install:
  - docker --version
  - docker-compose --version
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - npm install

script:
  - sudo docker-compose build subgraph
  - sudo docker-compose run subgraph test
  - sudo docker-compose run subgraph lint

after_script:
  - docker-compose down
