common: &common
  test_mnemonic: behave pipe turkey animal voyage dial relief menu blush match jeans general
mainnet:
  <<: *common
  addresses:
    Reputation: "0x13ad61aa8f695ce64711a51a6feccb48a275aaf8"
    ContributionReward: "0xc282f494a0619592a2410166dcc749155804f548"
development:
  <<: *common
  postgresPassword: "letmein"
