common: &common
  test_mnemonic: behave pipe turkey animal voyage dial relief menu blush match jeans general
mainnet:
  <<: *common
  addresses:
    GenesisProtocol: "0x8940442e7F54E875C8C1C80213A4Aee7EeE4781c"
    Reputation: "0x13ad61aa8f695ce64711a51a6feccb48a275aaf8"
    UController: "0xa50c298118e89e0cc465f2a1705c7579f67b6f26"
development:
  <<: *common
  postgresPassword: "letmein"
